### ISSUE TITLE
Work with multiple domains

### ISSUE THREAD

**Issue by btholt** [chrisyuska/auto-email#1]
Great library. This would be exactly what I was looking for if it supported an array of domains instead of just one.

**Comment by chrisyuska** [comment]
I actually kind of forgot about this plugin.  Adding support for multiple domains shouldn't be hard though.  I'll try getting around to adding it soon if I can find the time.

**Comment by Dottenpixel** [comment]
@btholt I was curious as to how you thought the multiple domains would work for the user. Since the auto-fill of the singular domain happens on entry of "@", what's your expectation when "@" is entered and there's multiple domains?

My feeling would be that the plugin wait for the subsequent entries after "@" to determine which domain to auto-fill. And in the case of something like ['example.com','example.net'], it would auto-fill "example." and wait for a "c" (for "com"), or "n" (for "net") to auto-fill the rest.

**Comment by chrisyuska** [comment]
I would actually argue that a desirable behavior would be to autocomplete the first matching domain in the array. If the array, `["gmail.com", "gonzo.com", "goo.com"]`, was passed, then "foobar@" was entered by the user, it would autocomplete to "foobar@gmail.com" with "gmail.com" highlighted.  If the user then enters "go," then "gonzo.com" would be the new highlighted domain.

Treating the array as an ordered list allows the developer to specify priority of domains (probably based on popularity), and it requires the fewest possible keystrokes a user would need for entering an email.

**Comment by btholt** [comment]
@chrisyuska nailed it. That's exactly what I would expect.

**Comment by Dottenpixel** [comment]
Yeah, I dig it @chrisyuska. I really like the ordered list idea.

**Comment by btholt** [comment]
So, I did it. [Here's my fork](https://github.com/btholt/auto-email). I took out your semicolon and comma completion stuff because I'm only using it on a singular input field. I'm not sure if that functionality was important to you,  but if it wasn't I'm more than happy for to pull request my code to this repo.

If not, feel free to take what I've done and implement as you see fit. Or not. :smile:

**Comment by Dottenpixel** [comment]
@btholt In regards to multiple domains, this works beautifully. Nice work!

I made a play pen: http://cdpn.io/GJzom

**Comment by chrisyuska** [comment]
@btholt's fork has been merged and modified to work with multiple emails, so this issue can be closed now.
